### ISSUE TITLE
Add display rotation instructions to README

### ISSUE THREAD

**Issue by lazd** [jlempen/Surface-Go-2-OpenCore#14] opened 2024-01-24 07:35 UTC
I'm happy to report display rotation works just fine with [Display Rotation Menu](https://www.magesw.com/displayrotation/) from Mage Software! Previously, when I tried this, I remember that scroll direction was reversed, but that's not the case now.

<img width="640" alt="Screenshot 2024-01-23 at 11 27 57 PM" src="https://github.com/jlempen/Surface-Go-2-OpenCore/assets/201344/53521ed0-0bd3-4353-9b6b-2a09b28cac92">

Not all the HiDPI options are available, really only 640x960 is usable, but it's pretty cramped.

<img width="827" alt="Screenshot 2024-01-23 at 11 34 31 PM" src="https://github.com/jlempen/Surface-Go-2-OpenCore/assets/201344/b28b3312-a66c-4fde-8dd8-864a65fbb167">

**Comment by jlempen** [comment] 2024-01-24 23:06
Interesting that you mention this, as it was the next thing on my to-do list :-)

The last time I played around with Mage Software's Display Rotation Menu, it would only work properly with the native display resolution of 1920x1280. Rotating the display with another HiDPI resolution set, the display would rotate correctly, but the display would only show a black screen with a mouse cursor. Furthermore, the touchscreen would stay in landscape mode making the whole operation useless. The only way to restore the landscape orientation was using the keyboard shortcut CTRL-OPTION-COMMAND-0 (as in "zero").

Today it seems to be working very nicely even with a HiDPI resolution such as 1152x768, which is the Default and most usable HiDPI resolution on the SGO2.

The first time you rotate the display to a portrait orientation, the resolution is set to 1280x1920, which is way too small for the SGO2's display. You'll need to head over to the display settings and set the only other available resolution, 640x960, which is quite perfect on our display in portrait orientation.

It may be possible to add custom resolutions with tools such as [RDM](https://github.com/usr-sse2/RDM), we'll have to play around with that stuff.

Now there are a few things that need to be sorted out:

Once the display is in portrait orientation, the menu bar won't show the Display Rotation Menu widget because there's not enough space for widgets in the menu bar (as is clearly visible in the first screenshot of the first post of this thread). So the only way to rotate back to landscape orientation is through the display rotation ootion in the Display settings. Or by attaching the Type Cover and hitting the keyboard shortcut CTRL-OPTION-COMMAND-0 (as in "zero").
The most elegant solution would be to find a way to integrate the Display Rotation Menu widget into the Control Center.
I could also imagine a few elegant solutions using the quite excellent [BetterTouchTool](https://folivora.ai/) to define one or several rotation gestures. 
Or even a desktop shortcut to trigger rotation actions through a script. The [displayplacer](https://github.com/jakehilborn/displayplacer) command line tool has a few options to rotate the display from the command line and could therefore be helpful for this task.

And while we're at it, there's already a nice configurable onscreen keyboard available in macOS's Accessibility settings. There's also an option to show the onscreen keyboard on the login screen.

**Comment by jlempen** [comment] 2024-01-24 23:34
OK, so a quick test with BetterTouchTool confirms that custom gestures for the Trackpad are indeed triggered by the touchscreen as well.

I assigned the aforementioned CTRL-OPTION-COMMAND-0 (as in "zero") keyboard shortcut to a 4 Finger Double Tap to restore landscape orientation and the display rotates back to landscape as intended when I double tap with four fingers on the touchscreen. Nice!

Knowing this, it should be quite trivial to program BetterTouchTool with custom gestures for every rotation angle. Or a logical gesture such as a clockwise circle to rotate the display clockwise by 90 degrees and a counterclockwise circle to rotate the display counterclockwise by 90 degrees, for example.

**Comment by lazd** [comment] 2024-01-25 02:42
> OK, so a quick test with BetterTouchTool confirms that custom gestures for the Trackpad are indeed triggered by the touchscreen as well.

Oh totally! I have tons of gestures setup for dictation, onscreen keyboard, close window, maximize window (with Rectangle), etc etc. Go wild with it!

**Comment by jlempen** [comment] 2024-07-17 00:14
Closed by https://github.com/jlempen/Surface-Go-2-OpenCore/commit/392433afe7cdbae5831abfd9f291c4035475947c

**Closed by jlempen** 2024-07-17 00:14 UTC
